// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaacvLE4UfrLp8VF3JXvsiWqqfKZ2v00E',
    appId: '1:629801883884:web:cf221330c664d03ae1edc9',
    messagingSenderId: '629801883884',
    projectId: 'arena-assist',
    authDomain: 'arena-assist.firebaseapp.com',
    storageBucket: 'arena-assist.firebasestorage.app',
    measurementId: 'G-M59YMCR9HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp6gCwr8A46GXxAdXm8b4w87iWUrP71P4',
    appId: '1:629801883884:android:bbf9a3353046a998e1edc9',
    messagingSenderId: '629801883884',
    projectId: 'arena-assist',
    storageBucket: 'arena-assist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEA4TL486GLA5jAeHQYzp9oo3Mt6wiwTs',
    appId: '1:629801883884:ios:bac6f9af836bb67de1edc9',
    messagingSenderId: '629801883884',
    projectId: 'arena-assist',
    storageBucket: 'arena-assist.firebasestorage.app',
    iosBundleId: 'com.example.arenaAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEA4TL486GLA5jAeHQYzp9oo3Mt6wiwTs',
    appId: '1:629801883884:ios:bac6f9af836bb67de1edc9',
    messagingSenderId: '629801883884',
    projectId: 'arena-assist',
    storageBucket: 'arena-assist.firebasestorage.app',
    iosBundleId: 'com.example.arenaAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaacvLE4UfrLp8VF3JXvsiWqqfKZ2v00E',
    appId: '1:629801883884:web:ffacf4bb50e8634ce1edc9',
    messagingSenderId: '629801883884',
    projectId: 'arena-assist',
    authDomain: 'arena-assist.firebaseapp.com',
    storageBucket: 'arena-assist.firebasestorage.app',
    measurementId: 'G-CCGG3RSW8S',
  );
}
